"""Add followers to users

Revision ID: 919220df13fb
Revises: 40069e88f059
Create Date: 2018-06-12 11:23:00.694707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919220df13fb'
down_revision = '40069e88f059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
